### PR TITLE
New Docker build approach

### PR DESCRIPTION
**Pull request by Joshua-Anderson**
This is a docker file based approach that takes the compiled app and sets it up in nginx.

It writes `$DEIS_CONTROLLER` to controller.js on start up, allowing controller customization.

I'm using alpine linux which means that the entire docker file is **_tiny**_.

This is very different from the current approach, so we should discuss if this is the way to go.
#### Advantages
1. Super tiny
2. Nginx will be faster and cleaner than node
#### Disadvantages
1. Need to build locally, can't build on docker hub becuase you must run `grunt build` before `docker build`.

### CODE REVIEW

**Comment by olalonde** [comment]
Suggestion: 

Keep current Dockerfile for local builds, rename to `Dockerfile.build` and mount `./dist` to `/app/dist` when running the container. This will create the static files in local `dist/` folder which can then be copied by your Nginx Dockerfile.

Still I think this solution might be a bit overkill just to save a bit of disk space / bandwidth. But if @jumbojett can maintain a Docker image on docker hub that we can all just `deis pull` to install, I won't complain :)

**Comment by Joshua-Anderson** [comment]
Unfortunately, I don't think that these two strategies can co-exist given that they need completely different methods for pointing to the deis controller, as yours in compiled in and mine is loaded at startup. I think that the size is not trivial, as you have to pull all of ubuntu and nodejs. If we can get a setup where `deis pull` instantly works, we will get a lot more users.

**Comment by Joshua-Anderson** [comment]
I agree that there are perks to your setup, so I'm ok if my way turns out to be too overkill for our needs. Automated builds might be worth the extra download time, since the local registry might already have ubuntu installed and nodejs can be cached for future downloads.

**Comment by olalonde** [comment]
If @jumbojett doesn't mind maintaining an image on the Docker registry, I agree it's worth putting the effort into making the container smaller/more efficient so that end users can just install with a `deis pull`. But otherwise, I don't think it's great to require users to have npm/grunt/bower installed on their local machine to build and deploy (in fact, the idea of having a separate `Dockerfile.build` file was so that it could be used to run a deterministic build on a local docker install and avoid problems with npm/grunt/bower).

**Comment by jumbojett** [comment]
This is great. @Joshua-Anderson I'm interested in using alpine as well. (Thanks for the link @bacongobbler) 

@olalonde has put together a working solution right now. I'm not keen on having multiple dockerfiles or a local build step.

There might be another option. Here's my current thought trail. All input is welcome.

Goals:
- tiny docker image based of alpine 
- nginx serving assets instead of nodejs
- minimal configuration for end-user
- single docker file

Plan:
- Add a `/dist` to the repository
- Convention over configuration. Rather than have a user specify a Deis api endpoint, require the UI be deployed under the same domain and have javascript reference relative paths. This would eliminate a custom build step to add the API URI to the javascript controller.

**Pull request closed without merging**
